module.exports = {
  apps: [
    {
      name: "einkaufsliste-backend",
      script: "server.js",
      cwd: "./backend",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
    },
    {
      name: "einkaufsliste-api",
      script: "admin_server.py",
      cwd: "./api",
      interpreter: "python3",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        PYTHONPATH: ".",
        PORT: 8000,
      },
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      log_file: "./logs/api-combined.log",
      time: true,
    },
    {
      name: "einkaufsliste-frontend",
      script: "serve",
      cwd: "./frontend",
      args: "-s build -p 3000",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
    },
    {
      name: "einkaufsliste-webhook",
      script: "webhook.py",
      cwd: "./",
      interpreter: "python3",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        GITHUB_WEBHOOK_SECRET: "einkaufsliste-webhook-secret",
        WEBHOOK_PORT: "9000",
        REPO_PATH: "/home/einkaufsliste",
      },
      error_file: "./logs/webhook-error.log",
      out_file: "./logs/webhook-out.log",
      log_file: "./logs/webhook-combined.log",
      time: true,
    },
  ],
};
