module.exports = {
  apps: [
    {
      name: "einkaufsliste-backend",
      script: "server.js",
      cwd: "./backend",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
        JWT_SECRET:
          process.env.JWT_SECRET || "CHANGE_THIS_JWT_SECRET_IN_PRODUCTION",
        ADMIN_PASSWORD:
          process.env.ADMIN_PASSWORD || "CHANGE_THIS_ADMIN_PASSWORD",
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
      merge_logs: true,
      combine_logs: true,
    },
    {
      name: "einkaufsliste-api",
      script: "admin_server.py",
      cwd: "./api",
      interpreter: "python3",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        PYTHONPATH: ".",
        PORT: 8000,
        PYTHONUNBUFFERED: "1",
      },
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      log_file: "./logs/api-combined.log",
      time: true,
      merge_logs: true,
      combine_logs: true,
    },
    {
      name: "einkaufsliste-frontend",
      script: "npx",
      cwd: "./frontend",
      args: "serve -s build -l 3000 --verbose",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        DEBUG: "*",
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
      merge_logs: true,
      combine_logs: true,
    },
    {
      name: "einkaufsliste-webhook",
      script: "webhook.py",
      cwd: "./",
      interpreter: "python3",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        GITHUB_WEBHOOK_SECRET: "einkaufsliste-webhook-secret",
        WEBHOOK_PORT: "9000",
        REPO_PATH: "/home/einkaufsliste",
        PYTHONUNBUFFERED: "1",
      },
      error_file: "./logs/webhook-error.log",
      out_file: "./logs/webhook-out.log",
      log_file: "./logs/webhook-combined.log",
      time: true,
      merge_logs: true,
      combine_logs: true,
    },
  ],
};
